### ISSUE TITLE
Add status information to active proposals?

### ISSUE THREAD

**Issue by binki** [HaxeFoundation/haxe-evolution#16]
I think it would be very useful to see on active proposals their status. E.g., what version of Haxe they were implemented in (if implemented) or what milestone they are expected to make (if not yet completed). E.g., I am interested in seeing [HXP-0001](https://github.com/HaxeFoundation/haxe-evolution/blob/master/proposals/0001-any.md) exist. If I read the entire detailed contents I can see that there are hints that it might be available by Haxe-4. But it’s not very clear and requires digging.

I think showing the status on all proposals would become more useful in the future when at least one proposal is actually implemented so you can quickly check if you can use it yet.

**Comment by clemos** [comment]
I think `Any` is already implemented in 3.3.0rc1 (http://try.haxe.org/#2d45F)
But I agree there should be more publicity.

**Comment by Simn** [comment]
I agree it would be nice to have "Accepted in 3.3.0" or something on the proposals.

**Comment by Simn** [comment]
Done for both accepted proposals.
