### ISSUE TITLE
Quote delimited #if statements

### ISSUE THREAD

**Issue by 0b1kn00b** [HaxeFoundation/haxe-evolution#3]
Some libraries have non-identifier tokens, which can't be used in identifiers for #if statements, mostly "-". To make from and to functions for abstracts, it would be useful to help interop.

**Comment by nadako** [comment]
I'm not sure how from/to abstract methods are related here, but I'm pretty Haxe does define `a_b` for `a-b`, so you can use that. Anyway, this repository is for proper proposals, so if you have one, please submit a PR :)
