### ISSUE TITLE
Emoji reaction

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe-evolution#31]
While +1/-1 means agree/disagree obviously, I would like to express "this is irrelevant/off-topic" as well. How about using the "confused" emoji ?

**Comment by Simn** [comment]
Good idea!

I wish the GitHub emoji selection was a bit versatile. Of the 6 reactions available, 4 are variations of "positive"...

Feel free to edit the wiki entry accordingly.

**Comment by kevinresol** [comment]
Well, I can't edit the wiki.

**Comment by Simn** [comment]
Ah, they changed the default access for that (which I think is good). I've changed it back now though. :)
