### ISSUE TITLE
Global using at declaration site.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe-evolution#35]
The idea would is to allow `using` clauses on `enum`, `interface` and perhaps also `class` (although I don't see the use case there).

```haxe
enum Option<T> using OptionTools {
  Some(v:T);
  None;
}

class OptionTools {
  static public function map<In, Out>(o:Option<T>, f:In->Out):Option<Out> { 
    /* and so on */
  }
  /* and so forth */
}
```

This would globally apply the static extension, but only to the type being declared. It would solve https://github.com/HaxeFoundation/haxe-evolution/issues/10 - albeit in a slightly awkward way.

On interfaces it could also do some good:

```haxe
interface Iterable<T> using Lambda {
  function iterator():Iterator<T>;
}
```

**Comment by nadako** [comment]
That's an interesting idea!

**Comment by Simn** [comment]
I had this same idea before. I wonder if this should be implemented as a first step to solve #10. The second step would then be to automatically move function declarations in enums to such static extension classes, and add the `using OptionTools` implicitly.

On its own, I wonder if its worth it given that we have import.hx and can just add `using OptionTools` there. I agree this looks nicer, but I'm not sure it's enough to warrant a syntax change.

**Comment by RealyUniqueName** [comment]
`Import.hx` cannot be distributed with haxelib.

**Comment by back2dos** [comment]
Also, on second thought, I would like this for abstracts too as it allows dispatching on type parameters. Here's a poor example that hopefully still gets the point across:

```haxe
//Array.hx
@:coreType class Array<T> using ArrayTools { /* all methods except sort */ }
//ArrayTools.hx
class ArrayTools {
  static public function sort<T>(a:Array<T>, compare:T->T->Int):Void;
}
class NumericArrayTools {
  static public function sort<T:Float>(a:Array<T>):Void;
  static public function sum<T:Float>(a:Array<T>):T;
}
class DateArrayTools {
  static public function sort(a:Array<Date>):Void;
}
class ComparableArrayTools {
  static public function sort<T:{ function compare(that:T):Int; }>(a:Array<T>):Void;
}
```

**Comment by bendmorris** [comment]
>and perhaps also class (although I don't see the use case there)

It gives a nice method for adding "mixins" to your classes. Multiple classes can declare `using` with the same extension class. AFAIK you can only do this with tink/macros currently.

**Comment by RealyUniqueName** [comment]
@back2dos are you going to convert this idea to a proposal?

**Comment by Simn** [comment]
This needs a proper proposal. I can't speak for Nicolas, but I for one would genuinely consider it.

**Comment by kaikoga** [comment]
Whoa, I thought this had been already implemented, but was just closed and forgotten...

Is this going to become a proposal?

**Comment by FuriouZz** [comment]
Does not seem to works with abstract =/

**Comment by back2dos** [comment]
You should file a bug report, specifying which Haxe version you're using.
