### ISSUE TITLE
Are syntax suggestions acceptable?

### ISSUE THREAD

**Issue by kobi2187** [HaxeFoundation/haxe-evolution#4]
Just to know, whether syntax suggestions are acceptable here?
Haxe is pretty verbose, and could use some convenience syntax, in my opinion.

**Comment by kobi2187** [comment]
Another suggestion is to include some of the very nice haxe libraries that exist

**Comment by nadako** [comment]
new syntax has little chances, but any properly written proposal will be at least considered
