### ISSUE TITLE
iphone and android travis-ci ?

### ISSUE THREAD

**Issue by Justinfront** [HaxeFoundation/haxe-evolution#5]
Struggling to get NME's iosview to work even reading issues and trying to rebuild stuff.
https://github.com/HaxeFoundation/hxcpp/commit/7707d6ba51b1a72c5e9264510d17bd33750e49d9
https://github.com/HaxeFoundation/hxcpp/issues/504

I often consider Haxe's mobile abilities are the "Rails" feature of haxe so it's vital that they become more and more robust, think a setup with NME and hxcpp would be enough, perhaps this would provide nightly hxcpp's to go with Haxe ones or is that already?

**Please can we get Android and Iphone builds on Travis-CI . Found something on iphone travis-ci here:** 
https://www.objc.io/issues/6-build-tools/travis-ci/

_Sorry I have not created a pull request I was not sure of the right format and where I work are kind of funny about me creating opensource repositories ( they want me to send them every commit !!) so this seemed simpler._

**Comment by Justinfront** [comment]
I found NME has travis but does not test against latest haxe, and probably not ios.  
https://github.com/haxenme/nme/blob/master/.travis.yml
But I feel haxe travis needs to cover android and ios.

**Comment by nadako** [comment]
This is a good idea, but I'm not sure if it's easy to setup (pinging our master @andyli).
However this is not really the right place for this issue. It should go to haxe github issue tracker...

**Comment by andyli** [comment]
I have too little experience in making mobile apps so I'm not sure. However, I believe at least building the app in CI is doable. To actually run the app in an emulator or something may be harder.
