### ISSUE TITLE
Allow inline XML

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe-evolution#9]
In the old days of AS3 one can write XML directly in code:

``` as3
var xml:XML =
    <myXML>
        <valueOfMyVar>???</valueOfMyVar>
    </myXML>
```

Is there a reason Haxe doesn't support that? If there aren't any I would like to add a proposal for that.

**Comment by RealyUniqueName** [comment]
Please follow proposal guidelines: https://github.com/HaxeFoundation/haxe-evolution#how-to-submit-an-hxp

**Comment by kevinresol** [comment]
@RealyUniqueName thanks for the info and I have read that thoroughly beforehand.
This post isn't a proposal by its nature. It is more a prerequisite discussion.

If I should still start a proposal, without any detail but only the title and introduction/usage. I can do that.

**Comment by benmerckx** [comment]
If this would allow us to write html in a jsx kind of way that would be awesome.

**Comment by kevinresol** [comment]
Let's discuss in #12
